In [1]:
import numpy as np


In [2]:
# Задача 1

N = 10
x = np.arange(N,-1,-1)
x


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [3]:
# Задача 2

np.diag(np.arange(N, -1, -1))

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [4]:
# Задача 3

from numpy import linalg 

a = np.array([ [4,2,1],[1,3,0],[0,5,4] ])
b = np.array([4,12,-3])

linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [20]:
# Задача 4

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

cos_alike_2 = []

for user in users_stats:
    cos_alike_2.append((np.dot(user, next_user_stats) / (np.linalg.norm(user)*np.linalg.norm(next_user_stats))))

print(f'Покупатель номер {cos_alike_2.index(max(cos_alike_2))+1} наиболее похож на заданного покупателя, его показатель - {round(max(cos_alike_2),4)}')


Покупатель номер 8 наиболее похож на заданного покупателя, его показатель - 0.9487


Хотел попробовать сделать через заполнение словаря, но с выводом номера и его значения возникла проблема

In [ ]:
i = 1
cos_alike = {}


for user in users_stats:
    cos_alike.update({i:(np.dot(user, next_user_stats) / (np.linalg.norm(user)*np.linalg.norm(next_user_stats)))})
    i += 1


for key, value in cos_alike.items():
    if value == max(value):
         print(f'Покупатель номер {key} наиболее похож на заданного покупателя, его показател - {value}')
